server:
  port: 8040
spring:
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.cluster.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.cluster.ecommerce.notification.PaymentNotificationRequest
  mail:
    host: localhost
    port: 1025
    username: root
    password: root
    properties:
      mail:
        smtp:
          trust: "*"
        auth: "true"
        starttls:
          enable: "true"
        connectiontimeout: "5000"
        timeout: "3000"
        writeTimeout: "5000"